<?php

# This file was automatically generated by the MediaWiki installer.
# If you make manual changes, please keep track in case you need to
# recreate them later.

$IP = "/home/groups/openzaurus/htdocs/wiki";
ini_set( "include_path", ".:$IP:$IP/includes:$IP/languages" );
require_once( "includes/DefaultSettings.php" );

# If PHP's memory limit is very low, some operations may fail.
# ini_set( 'memory_limit', '20M' );

if ( $wgCommandLineMode ) {
	if ( isset( $_SERVER ) && array_key_exists( 'REQUEST_METHOD', $_SERVER ) ) {
		die( "This script must be run from the command line\n" );
	}
} elseif ( empty( $wgNoOutputBuffer ) ) {
	## Compress output if the browser supports it
	if( !ini_get( 'zlib.output_compression' ) ) @ob_start( 'ob_gzhandler' );
}

$wgSitename         = "OpenZaurus";

$wgScriptPath	    = "/wiki";
$wgScript           = "$wgScriptPath/index.php";
$wgRedirectScript   = "$wgScriptPath/redirect.php";
$wgArticlePath      = "/$1";

$wgStylePath        = "$wgScriptPath/skins";
$wgStyleDirectory   = "$IP/skins";
$wgLogo             = "$wgScriptPath/zaurus-wglogo.gif";

$wgUploadPath       = "$wgScriptPath/images";
$wgUploadDirectory  = "$IP/images";

$wgEnableEmail      = false;
$wgEnableUserEmail  = false;

## For a detailed description of the following switches see
## http://meta.wikimedia.org/Enotif and http://meta.wikimedia.org/Eauthent
## There are many more options for fine tuning available see
## /includes/DefaultSettings.php
## UPO means: this is also a user preference option
$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = false;

$wgDBprefix = "mw_";
$wgDBmysql4 = false;   # If you're on MySQL 3.x, this must be FALSE:
$wgDBmysql5 = false;   # Experimental charset support for MySQL 4.1/5.0.

## Shared memory settings
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = array();

## To enable image uploads, make sure the 'images' directory
## is writable, then uncomment this:
$wgEnableUploads   = true;
$wgUseImageResize  = true;
#$wgUseImageMagick = true;
#$wgImageMagickConvertCommand = "/usr/bin/convert";

## If you want to use image uploads under safe mode,
## create the directories images/archive, images/thumb and
## images/temp, and make them all writable. Then uncomment
## this, if it's not already uncommented:
$wgHashedUploadDirectory = false;

## If you have the appropriate support software installed
## you can enable inline LaTeX equations:
# $wgUseTeX			= true;
$wgMathPath         = "{$wgUploadPath}/math";
$wgMathDirectory    = "{$wgUploadDirectory}/math";
$wgTmpDirectory     = "{$wgUploadDirectory}/tmp";

$wgLocalInterwiki   = $wgSitename;

$wgLanguageCode = "en";

$wgProxyKey = "d630168d8a145e91dfc0f80eab98d79e061d8751c9eaf8f389f42236045058ec";

$wgEnableCreativeCommonsRdf = true;
$wgRightsPage = "OpenZaurus:Copyrights";
$wgRightsUrl = "http://creativecommons.org/licenses/by-nc-sa/2.5/";
$wgRightsText = "Attribution-NonCommercial-ShareAlike 2.5";
$wgRightsIcon = "http://creativecommons.org/images/public/somerights20.png";

$wgDiff3 = "";

# $wgCacheEpoch = '20060413190000';
require("extensions/TimestampNow.php");
require("extensions/Email.php");


# --- spam protection ---
# Disables account creation by anonymous visitors
#$wgGroupPermissions['*']['createaccount'] = false;
# Requires users to log in to edit pages
# $wgGroupPermissions['*']['edit'] = false;


# No need to show discussion pages for anonymous users.
$wgShowIPinHeader = false;

# Get rid of all skins except for MonoBook -- too much to support otherwise.
$wgSkipSkins = array(simple, chick, cologneblue, myskin, standard /* called Classic */, nostalgia);

require_once("SiteSettings.php");
?>
