#!/bin/bash

# Scott Bronson
# 3 June 2006


# This sucks putting the password on the command line but I don't know
# of any workable alternative...  At least nobody can run ps on the 
# BerliOS machines...

# The egrep gets rid of all rows in the user tables (passwords, etc) and
# some meaningless and volatile cache tables.

# The sed rewrites the mw_page tables to set all hit counts to 0 (they
# cause some pretty massive churn and are meaningless on a mirror anyway).
# It also sets the restrictions to 'sysop' so the edit link will never
# show up on a mirror.  It's totally straightforward except for the 2
# places where we have to match a single-quoted string with escapes.


mysqldump --add-drop-table -h db.berlios.de -u openzaurus --password=$PASSWORD openzaurus | \
  egrep -v "^INSERT INTO mw_(user.*|site_stats|hitcounter|watchlist|recentchanges|objectcache|transcache|searchindex) " | \
  sed -r "s/^(INSERT INTO mw_page VALUES \\([0-9]+,[0-9]+,'([^'\\]|[\\].)*',)'([^'\\]|[\\].)*',[0-9]+/\\1'sysop',0/"

