#!/bin/sh

# This script pulls the next revision of the data from svn.
# If there was a new revision, it goes on to dump the new data into
# the database, update the application data, and prepare the app
# for use.

# Note that this script will not pull down any application changes
# unless the database has also changed.  Why generate more traffic?

# Set FORCE=1 to force the script to run even if there are no
# changes to the master site.     i.e. run: FORCE=1 ./update-site

cd `dirname $0`
. ./config


echo OZWiki Mirror
echo -------------
echo
echo Started at `date --utc`


# First check to see if there are any new versions.
# If there are, svn up responds with "^Updated to rev ##".
# Else, if no changes, it responds "At rev ##".

if [ "x" == "x$FORCE" ]; then
	if svn up | tail -1 | grep -q ^At; then
		echo 'Already up to date.'
		echo Finished at `date --utc`
		exit 0
	fi
	echo Database changes down by `date`
else
	svn up
fi


# We have new data.  Load it into the databse.
./load-database
echo Data loaded by `date --utc`
echo


# Pull down any changes to the application
cd "$HTDOCS"
svn up
echo Application changes down by `date --utc`
echo

cd wiki
date --utc > mirror.stamp


# Finally, rebuild the fulltext index.
php maintenance/rebuildtextindex.php
echo Fulltext rebuilt by `date --utc`
echo


echo done.
